---
title: "Boxplots"
author: "Nicole Bednarik & Katie Thomas"
date: 27 March 2023
output:
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
    code_fold: show
---

```{r setup, include = FALSE}
# Load package libraries
library(plyr)
library(geiger)
library(caper)
library(plotly)
library(kableExtra)
library(gridExtra)
library(ggimage)
library(grid)
library(gtable)
library(cowplot)
library(knitr)
library(tidyverse)
# Markdown settings
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.height = 4.5, fig.width=8)
```

# Data

First we import our tidied salamander morphology & trait binary dataset with the residuals of a cornea ~ cube root of mass PGLS as a column.

```{r load-data}
# Import tidied salamander eye size and trait data
sal.res <- data.frame(read.csv("../Data/Tidy/salamanders_residuals_binary.csv", header=TRUE, na.strings=c("", "NA", " ","<1")))
sal.res.2 <- data.frame(read.csv("../Data/Tidy/salamanders_residuals_updated.csv", header=TRUE, na.strings=c("", "NA", " ", "<1")))
pupils <- data.frame(read.csv("../Data/Raw/pupils", header=TRUE, na.strings=c("", "NA", " ", "<1")))
# Quick look at data structure
str(sal.res)
str(sal.res.2)
sal.res <- sal.res[-c(35:460)]
```

Next, we import the amphibian tree from Jetz and Pyron (2019) that has been pruned to match the salamander species in this dataset.

```{r, fig.height=18, fig.width=7}

#Import pruned phylogeny
caudatatree <- read.nexus("../Data/Tidy/caudata-tree.nex")

#Plot tree
plot.phylo(caudatatree, show.tip.label=TRUE, cex = 0.7)

```

```{r}
#boxplot of cornea diameter vs aquatic ecology
aquatic.abs <- ggplot(data = filter(sal.res, !is.na(Aquatic)), aes(x = Aquatic, y = cor_av)) +
  geom_boxplot(notch = FALSE, outlier.shape = NA) +
  stat_summary(fun.y = mean, colour="black", geom="point", 
               shape=18, size=3, show_guide = FALSE) +
  geom_jitter(aes(text = Genus_Species), 
              shape = 19, size = 1.3, alpha = 0.3, position = position_jitter(0.15)) +
  theme(text = element_text(size=14), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.text = element_text(angle = 0, size = 9)) +
  ylab("Mean cornea diameter (mm)") +
  xlab("Aquatic ecology") +
  theme(legend.position = "none")
#print plot
aquatic.abs
```
```{r}
#boxplot of pgls residuals vs. aquatic ecology (relative eye size)
aquatic.rel <- ggplot(data = filter(sal.res, !is.na(Aquatic)), aes(x = Aquatic, y = pglsres.cdmass)) +
  geom_boxplot(notch = FALSE, outlier.shape = NA) +
  stat_summary(fun.y = mean, colour="black", geom="point", 
               shape=18, size=3, show_guide = FALSE) +
  geom_jitter(aes(text = Genus_Species), 
              shape = 19, size = 1.3, alpha = 0.3, position = position_jitter(0.15)) +
  theme(text = element_text(size=14), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.text = element_text(angle = 0, size = 9)) +
  ylab("Relative cornea diameter (PGLS residuals)") +
  xlab("Aquatic ecology") +
  theme(legend.position = "none")
#print plot
aquatic.rel
```

##Pupil shape vs mass
```{r}
#boxplot of pupil shape vs mass
pupmass.abs <- ggplot(data = filter(sal.res, !is.na(Semiaquatic)), aes(x = Semiaquatic, y = cor_av)) +
  geom_boxplot(notch = FALSE, outlier.shape = NA) +
  stat_summary(fun.y = mean, colour="black", geom="point", 
               shape=18, size=3, show_guide = FALSE) +
  geom_jitter(aes(text = Genus_Species), 
              shape = 19, size = 1.3, alpha = 0.3, position = position_jitter(0.15)) +
  theme(text = element_text(size=14), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.text = element_text(angle = 0, size = 9)) +
  ylab("Mean cornea diameter (mm)") +
  xlab("Semiaquatic ecology") +
  theme(legend.position = "none")
#print plot
semiaquatic.abs
```
```{r}
#boxplot of pgls residuals vs. semiaquatic ecology (relative eye size)
semiaquatic.rel <- ggplot(data = filter(sal.res, !is.na(Semiaquatic)), aes(x = Semiaquatic, y = pglsres.cdmass)) +
  geom_boxplot(notch = FALSE, outlier.shape = NA) +
  stat_summary(fun.y = mean, colour="black", geom="point", 
               shape=18, size=3, show_guide = FALSE) +
  geom_jitter(aes(text = Genus_Species), 
              shape = 19, size = 1.3, alpha = 0.3, position = position_jitter(0.15)) +
  theme(text = element_text(size=14), panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  theme(axis.text = element_text(angle = 0, size = 9)) +
  ylab("Relative cornea diameter (PGLS residuals)") +
  xlab("Semiaquatic ecology") +
  theme(legend.position = "none")
#print plot
semiaquatic.rel
```